site_name: testmarkdown 
site_url: https://testmarkdown.readthedocs.org
repo_url: https://github.com/fabrizyo/testmarkdown.git
site_description: testmarkdown
docs_dir: doc
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["http://fiware.org/style/monokai_sublime.css"]
pages:
- 'Home': 'index.md'
- 'HomeREADME': 'README.md'
